/*
 AUTO PARC EXPORT — FICHIER FACILE À MODIFIER

 Pour ajouter une voiture : copiez simplement un bloc {...} dans la liste ci-dessous.
 Photos : mettez les fichiers dans le même dossier que index.html et indiquez leurs noms.
 10 à 15 photos sont recommandées.

 Les champs peuvent être laissés tels quels en français : les termes automobiles courants
 sont automatiquement traduits par le site. Pour une description parfaite dans les 6 langues,
 vous pouvez ajouter description:{fr:'...',en:'...',pl:'...',it:'...',es:'...',pt:'...'}.
*/
const autoparcVehicles = [
{
 id:'cla180', name:'Mercedes-Benz CLA 180 AMG', year:'2015', km:'152 000 km', fuel:'Essence', gear:'Boîte manuelle', price:'4 100 €', power:'122 ch', engine:'1.6 L', transmission:'Traction avant', color:'Gris', interior:'Cuir partiel', seats:'5', doors:'5', eu:"Jusqu'en août 2027", condition:'Excellent état', premium:false,
 description:{fr:'Mercedes-Benz CLA 180 AMG en excellent état, avec finition AMG, caméra de recul, navigation, climatisation automatique et nombreux équipements.',en:'Mercedes-Benz CLA 180 AMG in excellent condition, with AMG trim, rear-view camera, navigation, automatic climate control and extensive equipment.',pl:'Mercedes-Benz CLA 180 AMG w bardzo dobrym stanie, z pakietem AMG, kamerą cofania, nawigacją, automatyczną klimatyzacją i bogatym wyposażeniem.',it:'Mercedes-Benz CLA 180 AMG in ottime condizioni, con allestimento AMG, telecamera posteriore, navigazione, climatizzatore automatico e numerosi equipaggiamenti.',es:'Mercedes-Benz CLA 180 AMG en excelente estado, con acabado AMG, cámara de marcha atrás, navegación, climatizador automático y amplio equipamiento.',pt:'Mercedes-Benz CLA 180 AMG em excelente estado, com acabamento AMG, câmara traseira, navegação, climatização automática e amplo equipamento.'},
 equipmentByLang:{
  fr:['✓ Finition AMG<br>✓ Caméra de recul<br>✓ Radars avant & arrière<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Régulateur de vitesse','✓ Système multimédia<br>✓ Radio DAB+<br>✓ Navigation<br>✓ Climatisation automatique 2 zones<br>✓ Sièges avant chauffants','✓ Volant multifonction<br>✓ Phares Xénon<br>✓ Feux de jour LED<br>✓ Capteur de pluie<br>✓ Vitres électriques','✓ Rétroviseurs électriques rabattables<br>✓ Intérieur sport<br>✓ Isofix<br>✓ Jantes aluminium<br>✓ Pneus été et hiver sur jantes'],
  en:['✓ AMG trim<br>✓ Rear-view camera<br>✓ Front & rear parking sensors<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Cruise control','✓ Multimedia system<br>✓ DAB+ radio<br>✓ Navigation<br>✓ Dual-zone automatic climate control<br>✓ Heated front seats','✓ Multifunction steering wheel<br>✓ Xenon headlights<br>✓ LED daytime running lights<br>✓ Rain sensor<br>✓ Electric windows','✓ Electrically folding mirrors<br>✓ Sport interior<br>✓ Isofix<br>✓ Alloy wheels<br>✓ Summer and winter tyres on rims'],
  pl:['✓ Pakiet AMG<br>✓ Kamera cofania<br>✓ Czujniki parkowania przód i tył<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Tempomat','✓ System multimedialny<br>✓ Radio DAB+<br>✓ Nawigacja<br>✓ Automatyczna klimatyzacja 2-strefowa<br>✓ Podgrzewane fotele przednie','✓ Wielofunkcyjna kierownica<br>✓ Reflektory ksenonowe<br>✓ Światła dzienne LED<br>✓ Czujnik deszczu<br>✓ Elektryczne szyby','✓ Elektrycznie składane lusterka<br>✓ Sportowe wnętrze<br>✓ Isofix<br>✓ Felgi aluminiowe<br>✓ Opony letnie i zimowe na felgach'],
  it:['✓ Allestimento AMG<br>✓ Telecamera posteriore<br>✓ Sensori di parcheggio anteriori e posteriori<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Cruise control','✓ Sistema multimediale<br>✓ Radio DAB+<br>✓ Navigazione<br>✓ Climatizzatore automatico bizona<br>✓ Sedili anteriori riscaldabili','✓ Volante multifunzione<br>✓ Fari allo xeno<br>✓ Luci diurne LED<br>✓ Sensore pioggia<br>✓ Alzacristalli elettrici','✓ Specchietti elettrici ripiegabili<br>✓ Interni sportivi<br>✓ Isofix<br>✓ Cerchi in alluminio<br>✓ Pneumatici estivi e invernali su cerchi'],
  es:['✓ Acabado AMG<br>✓ Cámara de marcha atrás<br>✓ Sensores de aparcamiento delanteros y traseros<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Control de crucero','✓ Sistema multimedia<br>✓ Radio DAB+<br>✓ Navegación<br>✓ Climatizador automático de 2 zonas<br>✓ Asientos delanteros calefactados','✓ Volante multifunción<br>✓ Faros de xenón<br>✓ Luces diurnas LED<br>✓ Sensor de lluvia<br>✓ Elevalunas eléctricos','✓ Retrovisores eléctricos plegables<br>✓ Interior deportivo<br>✓ Isofix<br>✓ Llantas de aluminio<br>✓ Neumáticos de verano e invierno en llantas'],
  pt:['✓ Acabamento AMG<br>✓ Câmara traseira<br>✓ Sensores de estacionamento dianteiros e traseiros<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Cruise control','✓ Sistema multimédia<br>✓ Rádio DAB+<br>✓ Navegação<br>✓ Climatização automática de 2 zonas<br>✓ Bancos dianteiros aquecidos','✓ Volante multifunções<br>✓ Faróis de xénon<br>✓ Luzes diurnas LED<br>✓ Sensor de chuva<br>✓ Vidros elétricos','✓ Retrovisores elétricos rebatíveis<br>✓ Interior desportivo<br>✓ Isofix<br>✓ Jantes de alumínio<br>✓ Pneus de verão e inverno em jantes']
 },
 photos:Array.from({length:16},(_,i)=>`./cla180-${i+1}.jpg`)
},
{
 id:'tucson', name:'Hyundai Tucson Premium 4x4', year:'2016', km:'171 000 km', fuel:'Diesel', gear:'Boîte automatique', price:'5 700 €', power:'136 ch', engine:'2.0 L CRDi', transmission:'4x4', color:'Blanc', interior:'Cuir', seats:'5', doors:'5', owners:'2', eu:"Jusqu'en juin 2027", premium:true,
 description:{fr:'SUV familial spacieux et polyvalent, avec moteur 2.0 CRDi de 136 ch, transmission intégrale 4x4 et une dotation Premium complète.',en:'Spacious and versatile family SUV with a 2.0 CRDi 136 hp engine, four-wheel drive and a complete Premium specification.',pl:'Przestronny i wszechstronny rodzinny SUV z silnikiem 2.0 CRDi o mocy 136 KM, napędem 4x4 i bogatym wyposażeniem Premium.',it:'SUV familiare spazioso e versatile, con motore 2.0 CRDi da 136 CV, trazione integrale 4x4 e completa dotazione Premium.',es:'SUV familiar espacioso y versátil, con motor 2.0 CRDi de 136 CV, tracción integral 4x4 y completo equipamiento Premium.',pt:'SUV familiar espaçoso e versátil, com motor 2.0 CRDi de 136 cv, tração integral 4x4 e equipamento Premium completo.'},
 equipmentByLang:{
  fr:['✓ Édition Premium<br>✓ Boîte automatique<br>✓ Transmission 4x4<br>✓ Intérieur cuir<br>✓ Toit panoramique<br>✓ Sièges avant chauffants<br>✓ Sièges arrière chauffants','✓ Sièges avant ventilés<br>✓ Volant chauffant<br>✓ Caméra de recul<br>✓ Radars avant & arrière<br>✓ Avertisseur d’angle mort<br>✓ Navigation GPS<br>✓ Radio DAB+','✓ Bluetooth<br>✓ USB / AUX<br>✓ Démarrage sans clé<br>✓ Hayon électrique<br>✓ Régulateur de vitesse<br>✓ Climatisation automatique 2 zones<br>✓ Feux de jour LED','✓ Capteur de pluie<br>✓ Vitres électriques<br>✓ Rétroviseurs électriques rabattables<br>✓ Jantes alliage<br>✓ Pneus été sur jantes aluminium<br>✓ Pneus hiver sur jantes aluminium<br>✓ Isofix','✓ Volant multifonction<br>✓ Phares antibrouillard<br>✓ ABS & contrôle de stabilité'],
  en:['✓ Premium edition<br>✓ Automatic transmission<br>✓ 4x4 all-wheel drive<br>✓ Leather interior<br>✓ Panoramic roof<br>✓ Heated front seats<br>✓ Heated rear seats','✓ Ventilated front seats<br>✓ Heated steering wheel<br>✓ Rear-view camera<br>✓ Front & rear parking sensors<br>✓ Blind-spot warning<br>✓ GPS navigation<br>✓ DAB+ radio','✓ Bluetooth<br>✓ USB / AUX<br>✓ Keyless start<br>✓ Power tailgate<br>✓ Cruise control<br>✓ Dual-zone automatic climate control<br>✓ LED daytime running lights','✓ Rain sensor<br>✓ Electric windows<br>✓ Electrically folding mirrors<br>✓ Alloy wheels<br>✓ Summer tyres on alloy wheels<br>✓ Winter tyres on alloy wheels<br>✓ Isofix','✓ Multifunction steering wheel<br>✓ Fog lights<br>✓ ABS & stability control']
 },
 photos:Array.from({length:15},(_,i)=>`./tucson-${i+1}.jpg`)
},
{
 id:'i30', name:'Hyundai i30 1.4 T-GDi 140 ch', year:'2018', km:'71 000 km', fuel:'Essence', gear:'Boîte automatique', price:'3 200 €', power:'140 ch', engine:'1.4 T-GDi', transmission:'Traction avant', color:'Bleu métallisé', interior:'Cuir partiel', seats:'5', doors:'5', trunk:'395 L', eu:"Jusqu'au 26/06/2027", condition:'Excellent état',
 description:{fr:'Une Hyundai i30 élégante et très bien équipée, avec moteur essence 1.4 T-GDi de 140 ch, boîte automatique et seulement 71 000 km. Sa teinte bleu métallisé, son confort et ses équipements technologiques en font une excellente voiture polyvalente.',en:'An elegant and very well-equipped Hyundai i30 with a 1.4 T-GDi 140 hp petrol engine, automatic transmission and only 71,000 km. Its metallic blue finish, comfort and technology make it an excellent all-round vehicle.',pl:'Elegancki i bardzo dobrze wyposażony Hyundai i30 z benzynowym silnikiem 1.4 T-GDi o mocy 140 KM, automatyczną skrzynią biegów i przebiegiem zaledwie 71 000 km. Niebieski metalizowany kolor, komfort i nowoczesne wyposażenie czynią go bardzo uniwersalnym samochodem.',it:'Hyundai i30 elegante e molto ben equipaggiata, con motore benzina 1.4 T-GDi da 140 CV, cambio automatico e soli 71.000 km. Il colore blu metallizzato, il comfort e la tecnologia la rendono un’ottima auto versatile.',es:'Hyundai i30 elegante y muy bien equipada, con motor gasolina 1.4 T-GDi de 140 CV, cambio automático y solo 71.000 km. Su color azul metalizado, confort y tecnología la convierten en un vehículo muy versátil.',pt:'Hyundai i30 elegante e muito bem equipada, com motor a gasolina 1.4 T-GDi de 140 cv, caixa automática e apenas 71 000 km. A cor azul metalizada, o conforto e a tecnologia tornam este veículo muito versátil.'},
 equipmentByLang:{
  fr:['✓ Caméra de recul<br>✓ Navigation GPS<br>✓ Apple CarPlay / Android Auto<br>✓ Bluetooth – téléphone & musique<br>✓ Sièges avant chauffants<br>✓ Volant chauffant<br>✓ Sièges partiellement en cuir','✓ Siège conducteur électrique avec mémoire<br>✓ Démarrage sans clé<br>✓ Verrouillage sans clé<br>✓ Régulateur de vitesse adaptatif<br>✓ Reconnaissance des panneaux<br>✓ Capteurs de stationnement avant & arrière','✓ Assistance aux feux de route<br>✓ Assistance au maintien dans la voie<br>✓ Climatisation automatique 2 zones<br>✓ Feux de jour LED<br>✓ Capteur de pluie<br>✓ Volant multifonction','✓ Vitres électriques<br>✓ Rétroviseurs électriques<br>✓ Jantes aluminium<br>✓ Isofix<br>✓ ABS & contrôle de stabilité<br>✓ Alarme<br>✓ Phares antibrouillard'],
  en:['✓ Rear-view camera<br>✓ GPS navigation<br>✓ Apple CarPlay / Android Auto<br>✓ Bluetooth – phone & music<br>✓ Heated front seats<br>✓ Heated steering wheel<br>✓ Part-leather seats','✓ Electric driver’s seat with memory<br>✓ Keyless start<br>✓ Keyless locking<br>✓ Adaptive cruise control<br>✓ Traffic sign recognition<br>✓ Front & rear parking sensors','✓ High-beam assist<br>✓ Lane keep assist<br>✓ Dual-zone automatic climate control<br>✓ LED daytime running lights<br>✓ Rain sensor<br>✓ Multifunction steering wheel','✓ Electric windows<br>✓ Electric mirrors<br>✓ Alloy wheels<br>✓ Isofix<br>✓ ABS & stability control<br>✓ Alarm<br>✓ Fog lights']
 },
 photos:Array.from({length:15},(_,i)=>`./i30-${i+1}.jpg`)
}
];
