/*
 AUTO PARC EXPORT — FICHIER FACILE À MODIFIER

 Pour ajouter une voiture : copiez simplement un bloc {...} dans la liste ci-dessous.
 Photos : mettez les fichiers dans le même dossier que index.html et indiquez leurs noms.
 10 à 15 photos sont recommandées.

 Les champs peuvent être laissés tels quels en français : les termes automobiles courants
 sont automatiquement traduits par le site. Pour une description parfaite dans les 6 langues,
 vous pouvez ajouter description:{fr:'...',en:'...',pl:'...',it:'...',es:'...',pt:'...'}.
*/
const autoparcVehicles = [
{
 id:'cla180', name:'Mercedes-Benz CLA 180 AMG', year:'2015', km:'152 000 km', fuel:'Essence', gear:'Boîte manuelle', price:'4 100 €', power:'122 ch', engine:'1.6 L', transmission:'Traction avant', color:'Gris', interior:'Cuir partiel', seats:'5', doors:'5', eu:"Jusqu'en août 2027", condition:'Excellent état', premium:false,
 description:{fr:'Mercedes-Benz CLA 180 AMG en excellent état, avec finition AMG, caméra de recul, navigation, climatisation automatique et nombreux équipements.',en:'Mercedes-Benz CLA 180 AMG in excellent condition, with AMG trim, rear-view camera, navigation, automatic climate control and extensive equipment.',pl:'Mercedes-Benz CLA 180 AMG w bardzo dobrym stanie, z pakietem AMG, kamerą cofania, nawigacją, automatyczną klimatyzacją i bogatym wyposażeniem.',it:'Mercedes-Benz CLA 180 AMG in ottime condizioni, con allestimento AMG, telecamera posteriore, navigazione, climatizzatore automatico e numerosi equipaggiamenti.',es:'Mercedes-Benz CLA 180 AMG en excelente estado, con acabado AMG, cámara de marcha atrás, navegación, climatizador automático y amplio equipamiento.',pt:'Mercedes-Benz CLA 180 AMG em excelente estado, com acabamento AMG, câmara traseira, navegação, climatização automática e amplo equipamento.'},
 equipmentByLang:{
  fr:['✓ Finition AMG<br>✓ Caméra de recul<br>✓ Radars avant & arrière<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Régulateur de vitesse','✓ Système multimédia<br>✓ Radio DAB+<br>✓ Navigation<br>✓ Climatisation automatique 2 zones<br>✓ Sièges avant chauffants','✓ Volant multifonction<br>✓ Phares Xénon<br>✓ Feux de jour LED<br>✓ Capteur de pluie<br>✓ Vitres électriques','✓ Rétroviseurs électriques rabattables<br>✓ Intérieur sport<br>✓ Isofix<br>✓ Jantes aluminium<br>✓ Pneus été et hiver sur jantes'],
  en:['✓ AMG trim<br>✓ Rear-view camera<br>✓ Front & rear parking sensors<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Cruise control','✓ Multimedia system<br>✓ DAB+ radio<br>✓ Navigation<br>✓ Dual-zone automatic climate control<br>✓ Heated front seats','✓ Multifunction steering wheel<br>✓ Xenon headlights<br>✓ LED daytime running lights<br>✓ Rain sensor<br>✓ Electric windows','✓ Electrically folding mirrors<br>✓ Sport interior<br>✓ Isofix<br>✓ Alloy wheels<br>✓ Summer and winter tyres on rims'],
  pl:['✓ Pakiet AMG<br>✓ Kamera cofania<br>✓ Czujniki parkowania przód i tył<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Tempomat','✓ System multimedialny<br>✓ Radio DAB+<br>✓ Nawigacja<br>✓ Automatyczna klimatyzacja 2-strefowa<br>✓ Podgrzewane fotele przednie','✓ Wielofunkcyjna kierownica<br>✓ Reflektory ksenonowe<br>✓ Światła dzienne LED<br>✓ Czujnik deszczu<br>✓ Elektryczne szyby','✓ Elektrycznie składane lusterka<br>✓ Sportowe wnętrze<br>✓ Isofix<br>✓ Felgi aluminiowe<br>✓ Opony letnie i zimowe na felgach'],
  it:['✓ Allestimento AMG<br>✓ Telecamera posteriore<br>✓ Sensori di parcheggio anteriori e posteriori<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Cruise control','✓ Sistema multimediale<br>✓ Radio DAB+<br>✓ Navigazione<br>✓ Climatizzatore automatico bizona<br>✓ Sedili anteriori riscaldabili','✓ Volante multifunzione<br>✓ Fari allo xeno<br>✓ Luci diurne LED<br>✓ Sensore pioggia<br>✓ Alzacristalli elettrici','✓ Specchietti elettrici ripiegabili<br>✓ Interni sportivi<br>✓ Isofix<br>✓ Cerchi in alluminio<br>✓ Pneumatici estivi e invernali su cerchi'],
  es:['✓ Acabado AMG<br>✓ Cámara de marcha atrás<br>✓ Sensores de aparcamiento delanteros y traseros<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Control de crucero','✓ Sistema multimedia<br>✓ Radio DAB+<br>✓ Navegación<br>✓ Climatizador automático de 2 zonas<br>✓ Asientos delanteros calefactados','✓ Volante multifunción<br>✓ Faros de xenón<br>✓ Luces diurnas LED<br>✓ Sensor de lluvia<br>✓ Elevalunas eléctricos','✓ Retrovisores eléctricos plegables<br>✓ Interior deportivo<br>✓ Isofix<br>✓ Llantas de aluminio<br>✓ Neumáticos de verano e invierno en llantas'],
  pt:['✓ Acabamento AMG<br>✓ Câmara traseira<br>✓ Sensores de estacionamento dianteiros e traseiros<br>✓ Bluetooth<br>✓ USB / AUX<br>✓ Cruise control','✓ Sistema multimédia<br>✓ Rádio DAB+<br>✓ Navegação<br>✓ Climatização automática de 2 zonas<br>✓ Bancos dianteiros aquecidos','✓ Volante multifunções<br>✓ Faróis de xénon<br>✓ Luzes diurnas LED<br>✓ Sensor de chuva<br>✓ Vidros elétricos','✓ Retrovisores elétricos rebatíveis<br>✓ Interior desportivo<br>✓ Isofix<br>✓ Jantes de alumínio<br>✓ Pneus de verão e inverno em jantes']
 },
 photos:Array.from({length:15},(_,i)=>`./cla180-${i+1}.jpg`)
},
{
 id:'tucson', name:'Hyundai Tucson Premium 4x4', year:'2016', km:'171 000 km', fuel:'Diesel', gear:'Boîte automatique', price:'5 700 €', power:'136 ch', engine:'2.0 L CRDi', transmission:'4x4', color:'Blanc', interior:'Cuir', seats:'5', doors:'5', owners:'2', eu:"Jusqu'en juin 2027", premium:true,
 description:{fr:'SUV familial spacieux et polyvalent, avec moteur 2.0 CRDi de 136 ch, transmission intégrale 4x4 et une dotation Premium complète.',en:'Spacious and versatile family SUV with a 2.0 CRDi 136 hp engine, four-wheel drive and a complete Premium specification.',pl:'Przestronny i wszechstronny rodzinny SUV z silnikiem 2.0 CRDi o mocy 136 KM, napędem 4x4 i bogatym wyposażeniem Premium.',it:'SUV familiare spazioso e versatile, con motore 2.0 CRDi da 136 CV, trazione integrale 4x4 e completa dotazione Premium.',es:'SUV familiar espacioso y versátil, con motor 2.0 CRDi de 136 CV, tracción integral 4x4 y completo equipamiento Premium.',pt:'SUV familiar espaçoso e versátil, com motor 2.0 CRDi de 136 cv, tração integral 4x4 e equipamento Premium completo.'},
 equipmentByLang:{
  fr:['✓ Édition Premium<br>✓ Boîte automatique<br>✓ Transmission 4x4<br>✓ Intérieur cuir<br>✓ Toit panoramique<br>✓ Sièges avant chauffants<br>✓ Sièges arrière chauffants','✓ Sièges avant ventilés<br>✓ Volant chauffant<br>✓ Caméra de recul<br>✓ Radars avant & arrière<br>✓ Avertisseur d’angle mort<br>✓ Navigation GPS<br>✓ Radio DAB+','✓ Bluetooth<br>✓ USB / AUX<br>✓ Démarrage sans clé<br>✓ Hayon électrique<br>✓ Régulateur de vitesse<br>✓ Climatisation automatique 2 zones<br>✓ Feux de jour LED','✓ Capteur de pluie<br>✓ Vitres électriques<br>✓ Rétroviseurs électriques rabattables<br>✓ Jantes alliage<br>✓ Pneus été sur jantes aluminium<br>✓ Pneus hiver sur jantes aluminium<br>✓ Isofix','✓ Volant multifonction<br>✓ Phares antibrouillard<br>✓ ABS & contrôle de stabilité'],
  en:['✓ Premium edition<br>✓ Automatic transmission<br>✓ 4x4 all-wheel drive<br>✓ Leather interior<br>✓ Panoramic roof<br>✓ Heated front seats<br>✓ Heated rear seats','✓ Ventilated front seats<br>✓ Heated steering wheel<br>✓ Rear-view camera<br>✓ Front & rear parking sensors<br>✓ Blind-spot warning<br>✓ GPS navigation<br>✓ DAB+ radio','✓ Bluetooth<br>✓ USB / AUX<br>✓ Keyless start<br>✓ Power tailgate<br>✓ Cruise control<br>✓ Dual-zone automatic climate control<br>✓ LED daytime running lights','✓ Rain sensor<br>✓ Electric windows<br>✓ Electrically folding mirrors<br>✓ Alloy wheels<br>✓ Summer tyres on alloy wheels<br>✓ Winter tyres on alloy wheels<br>✓ Isofix','✓ Multifunction steering wheel<br>✓ Fog lights<br>✓ ABS & stability control']
 },
 photos:Array.from({length:15},(_,i)=>`./tucson-${i+1}.jpg`)
},
{
 id:'eniro64', name:'KIA e-NIRO 64 kWh EXCLUSIVE – 204 ch', year:'2021', km:'62 000 km', fuel:'Électricité', gear:'Boîte automatique', price:'13 000 €', power:'204 ch', engine:'64 kWh', transmission:'Traction avant', color:'Gris', interior:'Cuir noir', seats:'5', doors:'5', owners:'1', battery:'64 kWh', range:'455 km WLTP', manufacturerWarranty:'12/08/2028 ou 150 000 km', batteryWarranty:'12/08/2029', eu:"Jusqu'en août 2027", premium:true,
 description:{fr:'KIA e-NIRO 64 kWh EXCLUSIVE de 204 ch, 100 % électrique, avec 62 000 km et un seul propriétaire. Batterie 64 kWh offrant jusqu’à 455 km WLTP. Véhicule très bien équipé avec sellerie cuir, sièges avant chauffants et ventilés, sièges arrière chauffants, régulateur adaptatif ACC, caméra de recul, navigation, système audio JBL et préchauffage à distance.',en:'KIA e-NIRO 64 kWh EXCLUSIVE with 204 hp, fully electric, 62,000 km and one owner. 64 kWh battery with up to 455 km WLTP. Very well equipped with leather upholstery, heated and ventilated front seats, heated rear seats, adaptive cruise control, rear-view camera, navigation, JBL audio and remote pre-conditioning.',pl:'KIA e-NIRO 64 kWh EXCLUSIVE o mocy 204 KM, w pełni elektryczny, przebieg 62 000 km, jeden właściciel. Bateria 64 kWh zapewnia do 455 km WLTP. Bogate wyposażenie obejmuje skórzaną tapicerkę, podgrzewane i wentylowane fotele przednie, podgrzewane fotele tylne, adaptacyjny tempomat ACC, kamerę cofania, nawigację, system audio JBL i zdalne przygotowanie temperatury.',it:'KIA e-NIRO 64 kWh EXCLUSIVE da 204 CV, 100% elettrica, con 62.000 km e un solo proprietario. Batteria da 64 kWh con autonomia fino a 455 km WLTP. Molto ben equipaggiata con interni in pelle, sedili anteriori riscaldabili e ventilati, sedili posteriori riscaldabili, cruise control adattivo ACC, telecamera posteriore, navigazione, impianto audio JBL e preclimatizzazione a distanza.',es:'KIA e-NIRO 64 kWh EXCLUSIVE de 204 CV, 100% eléctrica, con 62.000 km y un solo propietario. Batería de 64 kWh con hasta 455 km WLTP. Muy bien equipada con tapicería de cuero, asientos delanteros calefactados y ventilados, asientos traseros calefactados, control de crucero adaptativo ACC, cámara trasera, navegación, sistema de audio JBL y preclimatización a distancia.',pt:'KIA e-NIRO 64 kWh EXCLUSIVE de 204 cv, 100% elétrica, com 62 000 km e um único proprietário. Bateria de 64 kWh com autonomia até 455 km WLTP. Muito bem equipada com estofos em couro, bancos dianteiros aquecidos e ventilados, bancos traseiros aquecidos, cruise control adaptativo ACC, câmara traseira, navegação, sistema de áudio JBL e pré-climatização à distância.'},
 equipmentByLang:{
  fr:['✓ Régulateur de vitesse adaptatif ACC<br>✓ Caméra de recul<br>✓ Radars avant & arrière<br>✓ Navigation GPS<br>✓ Sellerie cuir noir','✓ Siège conducteur électrique avec mémoire<br>✓ Sièges avant chauffants & ventilés<br>✓ Sièges arrière chauffants<br>✓ Volant chauffant','✓ Préchauffage à distance via application<br>✓ Apple CarPlay & Android Auto<br>✓ Système audio JBL<br>✓ Chargeur smartphone par induction','✓ Accès et démarrage sans clé<br>✓ Feux LED<br>✓ Jantes alliage<br>✓ Pneus été et hiver<br>✓ Entretien annuel suivi<br>✓ Révision 2026 effectuée avant livraison','✓ Garantie constructeur jusqu’au 12/08/2028 ou 150 000 km<br>✓ Garantie batterie jusqu’au 12/08/2029'],
  en:['✓ Adaptive cruise control ACC<br>✓ Rear-view camera<br>✓ Front & rear parking sensors<br>✓ GPS navigation<br>✓ Black leather upholstery','✓ Electric driver’s seat with memory<br>✓ Heated & ventilated front seats<br>✓ Heated rear seats<br>✓ Heated steering wheel','✓ Remote pre-conditioning via app<br>✓ Apple CarPlay & Android Auto<br>✓ JBL audio system<br>✓ Wireless smartphone charger','✓ Keyless entry and start<br>✓ LED lights<br>✓ Alloy wheels<br>✓ Summer and winter tyres<br>✓ Annual service history<br>✓ 2026 service completed before delivery','✓ Manufacturer warranty until 12/08/2028 or 150,000 km<br>✓ Battery warranty until 12/08/2029'],
  pl:['✓ Adaptacyjny tempomat ACC<br>✓ Kamera cofania<br>✓ Czujniki parkowania przód i tył<br>✓ Nawigacja GPS<br>✓ Czarna skórzana tapicerka','✓ Elektryczny fotel kierowcy z pamięcią<br>✓ Podgrzewane i wentylowane fotele przednie<br>✓ Podgrzewane fotele tylne<br>✓ Podgrzewana kierownica','✓ Zdalne przygotowanie temperatury przez aplikację<br>✓ Apple CarPlay i Android Auto<br>✓ System audio JBL<br>✓ Bezprzewodowa ładowarka telefonu','✓ Dostęp i uruchamianie bez kluczyka<br>✓ Oświetlenie LED<br>✓ Felgi aluminiowe<br>✓ Opony letnie i zimowe<br>✓ Coroczny serwis<br>✓ Przegląd 2026 wykonany przed wydaniem','✓ Gwarancja producenta do 12.08.2028 lub 150 000 km<br>✓ Gwarancja na baterię do 12.08.2029'],
  it:['✓ Cruise control adattivo ACC<br>✓ Telecamera posteriore<br>✓ Sensori di parcheggio anteriori e posteriori<br>✓ Navigazione GPS<br>✓ Rivestimento in pelle nera','✓ Sedile conducente elettrico con memoria<br>✓ Sedili anteriori riscaldabili e ventilati<br>✓ Sedili posteriori riscaldabili<br>✓ Volante riscaldabile','✓ Preclimatizzazione a distanza tramite app<br>✓ Apple CarPlay e Android Auto<br>✓ Impianto audio JBL<br>✓ Caricatore wireless per smartphone','✓ Accesso e avviamento senza chiave<br>✓ Luci LED<br>✓ Cerchi in lega<br>✓ Pneumatici estivi e invernali<br>✓ Manutenzione annuale documentata<br>✓ Tagliando 2026 eseguito prima della consegna','✓ Garanzia del costruttore fino al 12/08/2028 o 150.000 km<br>✓ Garanzia batteria fino al 12/08/2029'],
  es:['✓ Control de crucero adaptativo ACC<br>✓ Cámara trasera<br>✓ Sensores de aparcamiento delanteros y traseros<br>✓ Navegación GPS<br>✓ Tapicería de cuero negro','✓ Asiento del conductor eléctrico con memoria<br>✓ Asientos delanteros calefactados y ventilados<br>✓ Asientos traseros calefactados<br>✓ Volante calefactado','✓ Preclimatización a distancia mediante aplicación<br>✓ Apple CarPlay y Android Auto<br>✓ Sistema de audio JBL<br>✓ Cargador inalámbrico para smartphone','✓ Acceso y arranque sin llave<br>✓ Luces LED<br>✓ Llantas de aleación<br>✓ Neumáticos de verano e invierno<br>✓ Mantenimiento anual documentado<br>✓ Revisión 2026 realizada antes de la entrega','✓ Garantía del fabricante hasta el 12/08/2028 o 150.000 km<br>✓ Garantía de batería hasta el 12/08/2029'],
  pt:['✓ Cruise control adaptativo ACC<br>✓ Câmara traseira<br>✓ Sensores de estacionamento dianteiros e traseiros<br>✓ Navegação GPS<br>✓ Estofos em couro preto','✓ Banco do condutor elétrico com memória<br>✓ Bancos dianteiros aquecidos e ventilados<br>✓ Bancos traseiros aquecidos<br>✓ Volante aquecido','✓ Pré-climatização à distância através da aplicação<br>✓ Apple CarPlay e Android Auto<br>✓ Sistema de áudio JBL<br>✓ Carregador sem fios para smartphone','✓ Acesso e arranque sem chave<br>✓ Luzes LED<br>✓ Jantes de liga leve<br>✓ Pneus de verão e inverno<br>✓ Manutenção anual documentada<br>✓ Revisão de 2026 efetuada antes da entrega','✓ Garantia do fabricante até 12/08/2028 ou 150 000 km<br>✓ Garantia da bateria até 12/08/2029']
 },
 photos:Array.from({length:15},(_,i)=>`./kia-eniro-${i+1}.jpg`)
},
{
 id:'i30', name:'Hyundai i30 1.4 T-GDi 140 ch', year:'2018', km:'71 000 km', fuel:'Essence', gear:'Boîte automatique', price:'3 200 €', power:'140 ch', engine:'1.4 T-GDi', transmission:'Traction avant', color:'Bleu métallisé', interior:'Cuir partiel', seats:'5', doors:'5', trunk:'395 L', eu:"Jusqu'au 26/06/2027", condition:'Excellent état',
 description:{fr:'Une Hyundai i30 élégante et très bien équipée, avec moteur essence 1.4 T-GDi de 140 ch, boîte automatique et seulement 71 000 km. Sa teinte bleu métallisé, son confort et ses équipements technologiques en font une excellente voiture polyvalente.',en:'An elegant and very well-equipped Hyundai i30 with a 1.4 T-GDi 140 hp petrol engine, automatic transmission and only 71,000 km. Its metallic blue finish, comfort and technology make it an excellent all-round vehicle.',pl:'Elegancki i bardzo dobrze wyposażony Hyundai i30 z benzynowym silnikiem 1.4 T-GDi o mocy 140 KM, automatyczną skrzynią biegów i przebiegiem zaledwie 71 000 km. Niebieski metalizowany kolor, komfort i nowoczesne wyposażenie czynią go bardzo uniwersalnym samochodem.',it:'Hyundai i30 elegante e molto ben equipaggiata, con motore benzina 1.4 T-GDi da 140 CV, cambio automatico e soli 71.000 km. Il colore blu metallizzato, il comfort e la tecnologia la rendono un’ottima auto versatile.',es:'Hyundai i30 elegante y muy bien equipada, con motor gasolina 1.4 T-GDi de 140 CV, cambio automático y solo 71.000 km. Su color azul metalizado, confort y tecnología la convierten en un vehículo muy versátil.',pt:'Hyundai i30 elegante e muito bem equipada, com motor a gasolina 1.4 T-GDi de 140 cv, caixa automática e apenas 71 000 km. A cor azul metalizada, o conforto e a tecnologia tornam este veículo muito versátil.'},
 equipmentByLang:{
  fr:['✓ Caméra de recul<br>✓ Navigation GPS<br>✓ Apple CarPlay / Android Auto<br>✓ Bluetooth – téléphone & musique<br>✓ Sièges avant chauffants<br>✓ Volant chauffant<br>✓ Sièges partiellement en cuir','✓ Siège conducteur électrique avec mémoire<br>✓ Démarrage sans clé<br>✓ Verrouillage sans clé<br>✓ Régulateur de vitesse adaptatif<br>✓ Reconnaissance des panneaux<br>✓ Capteurs de stationnement avant & arrière','✓ Assistance aux feux de route<br>✓ Assistance au maintien dans la voie<br>✓ Climatisation automatique 2 zones<br>✓ Feux de jour LED<br>✓ Capteur de pluie<br>✓ Volant multifonction','✓ Vitres électriques<br>✓ Rétroviseurs électriques<br>✓ Jantes aluminium<br>✓ Isofix<br>✓ ABS & contrôle de stabilité<br>✓ Alarme<br>✓ Phares antibrouillard'],
  en:['✓ Rear-view camera<br>✓ GPS navigation<br>✓ Apple CarPlay / Android Auto<br>✓ Bluetooth – phone & music<br>✓ Heated front seats<br>✓ Heated steering wheel<br>✓ Part-leather seats','✓ Electric driver’s seat with memory<br>✓ Keyless start<br>✓ Keyless locking<br>✓ Adaptive cruise control<br>✓ Traffic sign recognition<br>✓ Front & rear parking sensors','✓ High-beam assist<br>✓ Lane keep assist<br>✓ Dual-zone automatic climate control<br>✓ LED daytime running lights<br>✓ Rain sensor<br>✓ Multifunction steering wheel','✓ Electric windows<br>✓ Electric mirrors<br>✓ Alloy wheels<br>✓ Isofix<br>✓ ABS & stability control<br>✓ Alarm<br>✓ Fog lights']
 },
 photos:Array.from({length:15},(_,i)=>`./i30-${i+1}.jpg`)
}

,
{
 id:'sprinter316', name:'Mercedes-Benz Sprinter 316 CDI', year:'2014', km:'158 500 km', fuel:'Diesel', gear:'Boîte manuelle', price:'13 500 €', power:'163 ch', engine:'2.1 L', transmission:'Propulsion arrière', color:'Blanc', interior:'Cuir MB-Tex', seats:'3', doors:'4', eu:"Jusqu'au 09/12/2027", premium:true,
 description:{fr:'Mercedes-Benz Sprinter 316 CDI de 2014, 163 ch, boîte manuelle 6 rapports et propulsion arrière. Très belle configuration professionnelle avec intérieur cuir MB-Tex, chauffage Webasto Diesel, phares xénon, feux de travail LED, attelage et aménagement intérieur professionnel. Dernier entretien réalisé en mars 2026.',en:'2014 Mercedes-Benz Sprinter 316 CDI with 163 hp, 6-speed manual transmission and rear-wheel drive. Very well-equipped professional configuration with MB-Tex leather interior, diesel Webasto heater, xenon headlights, LED work lights, tow hitch and professional interior racking. Last service carried out in March 2026.',pl:'Mercedes-Benz Sprinter 316 CDI z 2014 roku, 163 KM, manualną 6-biegową skrzynią i napędem na tył. Bardzo dobrze wyposażona konfiguracja użytkowa z tapicerką MB-Tex, ogrzewaniem Webasto Diesel, reflektorami ksenonowymi, światłami roboczymi LED, hakiem holowniczym i profesjonalną zabudową przestrzeni ładunkowej. Ostatni serwis wykonano w marcu 2026 roku.',it:'Mercedes-Benz Sprinter 316 CDI del 2014, 163 CV, cambio manuale a 6 marce e trazione posteriore. Ottima configurazione professionale con interni in MB-Tex, riscaldatore Webasto Diesel, fari allo xeno, luci da lavoro LED, gancio traino e allestimento professionale del vano di carico. Ultimo tagliando effettuato a marzo 2026.',es:'Mercedes-Benz Sprinter 316 CDI de 2014, 163 CV, cambio manual de 6 velocidades y propulsión trasera. Excelente configuración profesional con interior MB-Tex, calefacción Webasto Diesel, faros de xenón, luces de trabajo LED, enganche de remolque y equipamiento profesional del compartimento de carga. Último mantenimiento realizado en marzo de 2026.',pt:'Mercedes-Benz Sprinter 316 CDI de 2014, 163 cv, caixa manual de 6 velocidades e tração traseira. Excelente configuração profissional com interior em MB-Tex, aquecimento Webasto Diesel, faróis de xénon, luzes de trabalho LED, engate de reboque e equipamento profissional do compartimento de carga. Última manutenção realizada em março de 2026.'},
 equipmentByLang:{
  fr:['✓ Chauffage Webasto Diesel<br>✓ Phares xénon<br>✓ Feux de travail LED<br>✓ Climatisation Tempmatic<br>✓ Sièges chauffants','✓ Régulateur de vitesse<br>✓ Radio DAB+<br>✓ Bluetooth + USB<br>✓ ESP + assistance au vent latéral<br>✓ Rétroviseurs électriques chauffants','✓ 2 clés<br>✓ Attelage remorque – jusqu’à 2 000 kg<br>✓ Pneus été + hiver sur jantes<br>✓ Intérieur cuir MB-Tex','✓ Aménagement professionnel avec étagères et rangements<br>✓ Éclairage intérieur<br>✓ Roue(s) supplémentaire(s) visible(s) sur les photos<br>✓ Soubassement traité antirouille en 2026','✓ Garantie 3 mois / 3 000 km<br>✓ Contrôle technique UE valable jusqu’au 09/12/2027<br>✓ Dernier entretien : mars 2026'],
  en:['✓ Diesel Webasto heater<br>✓ Xenon headlights<br>✓ LED work lights<br>✓ Tempmatic air conditioning<br>✓ Heated seats','✓ Cruise control<br>✓ DAB+ radio<br>✓ Bluetooth + USB<br>✓ ESP + crosswind assist<br>✓ Electrically heated mirrors','✓ 2 keys<br>✓ Tow hitch – up to 2,000 kg<br>✓ Summer + winter tyres on rims<br>✓ MB-Tex leather interior','✓ Professional racking and storage system<br>✓ Interior lighting<br>✓ Additional wheel(s) visible in the photos<br>✓ Underbody treated against rust in 2026','✓ 3-month / 3,000 km warranty<br>✓ EU roadworthiness inspection valid until 09/12/2027<br>✓ Last service: March 2026'],
  pl:['✓ Ogrzewanie Webasto Diesel<br>✓ Reflektory ksenonowe<br>✓ Światła robocze LED<br>✓ Klimatyzacja Tempmatic<br>✓ Podgrzewane fotele','✓ Tempomat<br>✓ Radio DAB+<br>✓ Bluetooth + USB<br>✓ ESP + asystent bocznego wiatru<br>✓ Elektrycznie podgrzewane lusterka','✓ 2 kluczyki<br>✓ Hak holowniczy – do 2 000 kg<br>✓ Opony letnie + zimowe na felgach<br>✓ Wnętrze MB-Tex','✓ Profesjonalna zabudowa z półkami i schowkami<br>✓ Oświetlenie przestrzeni ładunkowej<br>✓ Dodatkowe koła widoczne na zdjęciach<br>✓ Podwozie zabezpieczone antykorozyjnie w 2026 roku','✓ Gwarancja 3 miesiące / 3 000 km<br>✓ Badanie techniczne UE ważne do 09.12.2027<br>✓ Ostatni serwis: marzec 2026'],
  it:['✓ Riscaldatore Webasto Diesel<br>✓ Fari allo xeno<br>✓ Luci da lavoro LED<br>✓ Climatizzatore Tempmatic<br>✓ Sedili riscaldabili','✓ Cruise control<br>✓ Radio DAB+<br>✓ Bluetooth + USB<br>✓ ESP + assistenza al vento laterale<br>✓ Specchietti elettrici riscaldabili','✓ 2 chiavi<br>✓ Gancio traino – fino a 2.000 kg<br>✓ Pneumatici estivi + invernali su cerchi<br>✓ Interni in MB-Tex','✓ Allestimento professionale con scaffali e vani portaoggetti<br>✓ Illuminazione del vano di carico<br>✓ Ruota/e aggiuntiva/e visibile/i nelle foto<br>✓ Sottoscocca trattato contro la ruggine nel 2026','✓ Garanzia 3 mesi / 3.000 km<br>✓ Revisione tecnica UE valida fino al 09/12/2027<br>✓ Ultimo tagliando: marzo 2026'],
  es:['✓ Calefacción Webasto Diesel<br>✓ Faros de xenón<br>✓ Luces de trabajo LED<br>✓ Climatización Tempmatic<br>✓ Asientos calefactados','✓ Control de crucero<br>✓ Radio DAB+<br>✓ Bluetooth + USB<br>✓ ESP + asistencia contra viento lateral<br>✓ Retrovisores eléctricos calefactados','✓ 2 llaves<br>✓ Enganche de remolque – hasta 2.000 kg<br>✓ Neumáticos de verano + invierno en llantas<br>✓ Interior MB-Tex','✓ Equipamiento profesional con estanterías y compartimentos<br>✓ Iluminación del compartimento de carga<br>✓ Rueda(s) adicional(es) visible(s) en las fotos<br>✓ Bajos tratados contra la corrosión en 2026','✓ Garantía de 3 meses / 3.000 km<br>✓ Inspección técnica UE válida hasta el 09/12/2027<br>✓ Último mantenimiento: marzo de 2026'],
  pt:['✓ Aquecimento Webasto Diesel<br>✓ Faróis de xénon<br>✓ Luzes de trabalho LED<br>✓ Climatização Tempmatic<br>✓ Bancos aquecidos','✓ Cruise control<br>✓ Rádio DAB+<br>✓ Bluetooth + USB<br>✓ ESP + assistência ao vento lateral<br>✓ Retrovisores elétricos aquecidos','✓ 2 chaves<br>✓ Engate de reboque – até 2 000 kg<br>✓ Pneus de verão + inverno em jantes<br>✓ Interior em MB-Tex','✓ Equipamento profissional com prateleiras e compartimentos<br>✓ Iluminação do compartimento de carga<br>✓ Roda(s) adicional(is) visível(is) nas fotos<br>✓ Parte inferior tratada contra a corrosão em 2026','✓ Garantia de 3 meses / 3 000 km<br>✓ Inspeção técnica UE válida até 09/12/2027<br>✓ Última manutenção: março de 2026']
 },
 photos:Array.from({length:15},(_,i)=>`./sprinter316-${i+1}.jpg`)
},
{
 id:'transitcustom290', name:'Ford Transit Custom 290L 2.0 TDCi', year:'2017', km:'128 000 km', fuel:'Diesel', gear:'Boîte manuelle', price:'5 700 €', power:'130 ch', engine:'2.0 L TDCi', transmission:'Traction avant', color:'Blanc', interior:'Tissu noir', seats:'3', premium:false,
 description:{fr:'Ford Transit Custom 290L 2.0 TDCi de 2017, 130 ch, boîte manuelle et traction avant. Utilitaire professionnel aménagé avec grand espace de chargement, caméra de recul, radars avant et arrière, attelage et équipements de confort. Courroie de distribution neuve et historique d’entretien disponible.',en:'2017 Ford Transit Custom 290L 2.0 TDCi, 130 hp, manual transmission and front-wheel drive. Professionally equipped van with a large load area, rear-view camera, front and rear parking sensors, tow hitch and comfort equipment. New timing belt and service history available.',pl:'Ford Transit Custom 290L 2.0 TDCi z 2017 roku, 130 KM, manualną skrzynią biegów i napędem na przednie koła. Profesjonalnie wyposażony samochód dostawczy z dużą przestrzenią ładunkową, kamerą cofania, czujnikami parkowania z przodu i z tyłu, hakiem holowniczym oraz wyposażeniem zapewniającym komfort. Nowy pasek rozrządu i dostępna historia serwisowa.',it:'Ford Transit Custom 290L 2.0 TDCi del 2017, 130 CV, cambio manuale e trazione anteriore. Veicolo commerciale allestito professionalmente con ampio spazio di carico, telecamera posteriore, sensori di parcheggio anteriori e posteriori, gancio traino e dotazioni di comfort. Cinghia di distribuzione nuova e storico manutenzione disponibile.',es:'Ford Transit Custom 290L 2.0 TDCi de 2017, 130 CV, cambio manual y tracción delantera. Vehículo comercial acondicionado profesionalmente con gran espacio de carga, cámara de marcha atrás, sensores de aparcamiento delanteros y traseros, enganche de remolque y equipamiento de confort. Correa de distribución nueva e historial de mantenimiento disponible.',pt:'Ford Transit Custom 290L 2.0 TDCi de 2017, 130 cv, caixa manual e tração dianteira. Veículo comercial preparado profissionalmente com grande espaço de carga, câmara traseira, sensores de estacionamento dianteiros e traseiros, engate de reboque e equipamentos de conforto. Correia de distribuição nova e histórico de manutenção disponível.'},
 equipmentByLang:{
  fr:['✓ Climatisation<br>✓ Régulateur de vitesse<br>✓ Caméra de recul<br>✓ Radars avant & arrière<br>✓ Radio DAB+<br>✓ Bluetooth + USB','✓ Attelage remorque<br>✓ Aménagement intérieur du chargement<br>✓ Plancher de chargement<br>✓ Chauffage moteur<br>✓ Rétroviseurs chauffants et rabattables','✓ Phares bi-xénon<br>✓ Jantes aluminium<br>✓ Pneus été + hiver<br>✓ Courroie de distribution neuve<br>✓ Grand espace de chargement','✓ Historique d’entretien disponible<br>✓ 3 places<br>✓ Traction avant<br>✓ Boîte manuelle','✓ Garantie occasion : 3 mois / 3 000 km<br>✓ Contrôle technique UE valable jusqu’en janvier 2027'],
  en:['✓ Air conditioning<br>✓ Cruise control<br>✓ Rear-view camera<br>✓ Front & rear parking sensors<br>✓ DAB+ radio<br>✓ Bluetooth + USB','✓ Tow hitch<br>✓ Interior load-area racking<br>✓ Load-area floor<br>✓ Engine heater<br>✓ Heated and folding mirrors','✓ Bi-xenon headlights<br>✓ Alloy wheels<br>✓ Summer + winter tyres<br>✓ New timing belt<br>✓ Large load area','✓ Service history available<br>✓ 3 seats<br>✓ Front-wheel drive<br>✓ Manual transmission','✓ Used-car warranty: 3 months / 3,000 km<br>✓ EU roadworthiness inspection valid until January 2027'],
  pl:['✓ Klimatyzacja<br>✓ Tempomat<br>✓ Kamera cofania<br>✓ Czujniki parkowania przód i tył<br>✓ Radio DAB+<br>✓ Bluetooth + USB','✓ Hak holowniczy<br>✓ Zabudowa przestrzeni ładunkowej<br>✓ Podłoga przestrzeni ładunkowej<br>✓ Ogrzewanie silnika<br>✓ Podgrzewane i składane lusterka','✓ Reflektory bi-ksenonowe<br>✓ Felgi aluminiowe<br>✓ Opony letnie + zimowe<br>✓ Nowy pasek rozrządu<br>✓ Duża przestrzeń ładunkowa','✓ Historia serwisowa dostępna<br>✓ 3 miejsca<br>✓ Napęd na przednie koła<br>✓ Skrzynia manualna','✓ Gwarancja samochodu używanego: 3 miesiące / 3 000 km<br>✓ Badanie techniczne UE ważne do stycznia 2027'],
  it:['✓ Climatizzatore<br>✓ Cruise control<br>✓ Telecamera posteriore<br>✓ Sensori di parcheggio anteriori e posteriori<br>✓ Radio DAB+<br>✓ Bluetooth + USB','✓ Gancio traino<br>✓ Allestimento interno del vano di carico<br>✓ Pavimento del vano di carico<br>✓ Riscaldatore del motore<br>✓ Specchietti riscaldabili e ripiegabili','✓ Fari bi-xeno<br>✓ Cerchi in alluminio<br>✓ Pneumatici estivi + invernali<br>✓ Cinghia di distribuzione nuova<br>✓ Ampio spazio di carico','✓ Storico manutenzione disponibile<br>✓ 3 posti<br>✓ Trazione anteriore<br>✓ Cambio manuale','✓ Garanzia veicolo usato: 3 mesi / 3.000 km<br>✓ Revisione tecnica UE valida fino a gennaio 2027'],
  es:['✓ Aire acondicionado<br>✓ Control de crucero<br>✓ Cámara de marcha atrás<br>✓ Sensores de aparcamiento delanteros y traseros<br>✓ Radio DAB+<br>✓ Bluetooth + USB','✓ Enganche de remolque<br>✓ Equipamiento interior del compartimento de carga<br>✓ Suelo del compartimento de carga<br>✓ Calentador del motor<br>✓ Retrovisores calefactados y plegables','✓ Faros bi-xenón<br>✓ Llantas de aluminio<br>✓ Neumáticos de verano + invierno<br>✓ Correa de distribución nueva<br>✓ Gran espacio de carga','✓ Historial de mantenimiento disponible<br>✓ 3 plazas<br>✓ Tracción delantera<br>✓ Cambio manual','✓ Garantía de vehículo usado: 3 meses / 3.000 km<br>✓ Inspección técnica UE válida hasta enero de 2027'],
  pt:['✓ Ar condicionado<br>✓ Cruise control<br>✓ Câmara traseira<br>✓ Sensores de estacionamento dianteiros e traseiros<br>✓ Rádio DAB+<br>✓ Bluetooth + USB','✓ Engate de reboque<br>✓ Equipamento interior do compartimento de carga<br>✓ Piso do compartimento de carga<br>✓ Aquecedor do motor<br>✓ Retrovisores aquecidos e rebatíveis','✓ Faróis bi-xénon<br>✓ Jantes de alumínio<br>✓ Pneus de verão + inverno<br>✓ Correia de distribuição nova<br>✓ Grande espaço de carga','✓ Histórico de manutenção disponível<br>✓ 3 lugares<br>✓ Tração dianteira<br>✓ Caixa manual','✓ Garantia de veículo usado: 3 meses / 3 000 km<br>✓ Inspeção técnica UE válida até janeiro de 2027']
 },
 photos:Array.from({length:14},(_,i)=>`./transitcustom290-${i+1}.jpg`)
}
];
